### ISSUE TITLE
Run linter?

### ISSUE THREAD

**Issue by jessemillar** [kobaltcore/renutil#1]
`renutil launch $(renutil list) distribute .` works great for generating distributions, but `renutil launch $(renutil list) lint .` errors. I'm guessing the default Ren'Py launcher doesn't accept `lint` as an argument (I assumed it would since `renpy.sh` does). Is there any way to run the linter via `renutil`?

Hopefully that's not a silly/obvious question. I'm new to Ren'Py.

**Comment by kobaltcore** [comment]
Hey, sorry for ghosting you, I didn't receive a notification for this issue. Sincere apologies.

This is unfortunately due to Ren'Py's strange way of handling the command line. Since `renutil` merely hands off all arguments to Ren'Py, its handling is what we must obey.

There are two things that are available when using Ren'Py from the command line:
1. Raw Ren'Py access
    - This runs projects
2. `Launcher` access
    - This runs the integrated `Launcher` project, which itself is a Ren'Py game

Unfortunately functionality is split between native Ren'Py access and the Launcher. The latter handles creating and building games while the former runs the Linter. We can think of the linter as *belonging to a given project* for this use-case.

Thus, to lint a given game, we must skip the `Launcher` project and use native access, which `renutil` already supports:
```bash
renutil launch -d $(renutil list) . lint
```

**Comment by jessemillar** [comment]
No problem! GitHub issue notifications are often more noise than signal.

Thank you very much for the explanation and example! That all makes perfect sense. Odd that Ren’Py architected things that way, but I understand things a lot more now.

[I created a Docker image](https://github.com/jessemillar/arch-renpy-build) that includes `renutil` and a couple other command line utilities. Now it can lint thanks to your help!
